#!/bin/bash
echo "🧪 测试 iFlow 集成..."
echo ""
echo "使用方法："
echo "  1. 在 OpenClaw 对话中输入：/model iflow-qwen-max"
echo "  2. 或者修改默认模型配置"
echo ""
echo "可用模型："
echo "  - iflow-qwen-max (推荐)"
echo "  - iflow-qwen-coder"
echo "  - iflow-kimi-k2"
echo "  - iflow-deepseek-v3"
echo "  - iflow-deepseek-r1"
echo "  - iflow-qwen-235b"
echo ""
echo "✅ iFlow 已配置完成！"
